# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=employee_schema

# Flyway Migration Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=employee_schema
spring.flyway.schemas=employee_schema
spring.flyway.create-schemas=true
#spring.flyway.baseline-on-migrate=true
#spring.flyway.baseline-version=0
spring.flyway.validate-on-migrate=true