CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE employee.employees (
                                           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                           name VARCHAR(100),
                                            age INTEGER,
                                            department VARCHAR(100),
                                            salary DOUBLE PRECISION

);