CREATE TABLE customer(
                         cid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         c_name VARCHAR(100)  ,
                        designation VARCHAR(100)
);