CREATE TABLE employee.employee_profile
(
    id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_no VARCHAR(100),
    city     VARCHAR(100),
    emp_id     BIGINT UNIQUE,

    CONSTRAINT fk_employee_profile FOREIGN KEY (emp_id) REFERENCES employee.employees (id)
);